### PR TITLE
Require frame-ancestors 'none' on admin panels

### PR DESCRIPTION
**Pull request by jvehent**
This came up during a discussion with @gdestuynder and seems good practice for admin panels anyway. Thoughts?

### CODE REVIEW

**Comment by kangsterizer** [comment]
I wonder if this attack has a name actually. Could be "reflected CSRF" if not.
This pretty much prevents this scenario:

- victim logged in onto SPA which stored a token in `localStorage`
- attacker has a page with an iframe and the iframe contains an SPA URL such as https://example.com/spa/delete_account
- victim loads attacker page, which loads the SPA in the iframe, which loads `/delete_account` and construct an API query with that trusted URL path
- SPA calls API to delete account, boo.

The difference with a normal CSRF is that you're probably not vulnerable to this by default as it requires:

- the SPA to be able to transparently fetch the token (storing it in `localStorage` enables that behavior)
- the SPA needs to be constructing API queries based on the GET query/parameters of the SPA itself (which it often does not) and call the API based on these

Adding the CSP rule prevents doing so via iframe at the minimum

**Review by g-k — APPROVED** [review]

**Comment by gdestuynder** [comment]
side-note: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options probably also fits the bill

**Review by psiinon — APPROVED** [review]
Yea. x-frame-options should handle this too, but think this is still worth adding.

**Comment by g-k** [comment]
freddy pointed out this could go by CS#RF or DOM-based CSRF https://twitter.com/kangsterizer/status/1118276990958571521

**Comment by jvehent** [comment]
I'll add a reference to that recording.

**Review by g-k — APPROVED** [review]

**Comment by g-k** [comment]
Landed in https://github.com/mozilla-services/websec-check/commit/00342a7650581e2af0c20e0e47498420372024fb

**Pull request closed without merging**
